"""Shared protocol constants for the chat application."""

from __future__ import annotations

ACTION_REGISTER = "register"
ACTION_LOGIN = "login"
ACTION_SEND_MESSAGE = "send_message"
ACTION_MESSAGE_DELIVERED = "message_delivered"
ACTION_TYPING = "typing"
ACTION_CREATE_ROOM = "create_room"
ACTION_JOIN_ROOM = "join_room"
ACTION_LEAVE_ROOM = "leave_room"
ACTION_GET_HISTORY = "get_history"
ACTION_GET_ROOMS = "get_rooms"
ACTION_GET_ROOM_MEMBERS = "get_room_members"
ACTION_DISCONNECT = "disconnect"
ACTION_PING = "ping"

EVENT_RESPONSE = "response"
EVENT_PRESENCE_UPDATE = "presence_update"
EVENT_NEW_MESSAGE = "new_message"
EVENT_TYPING_UPDATE = "typing_update"
EVENT_ROOM_UPDATE = "room_update"
EVENT_ERROR = "error"

STATUS_SUCCESS = "success"
STATUS_ERROR = "error"

ERROR_INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
ERROR_USER_EXISTS = "USER_EXISTS"
ERROR_RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
ERROR_UNAUTHORIZED = "UNAUTHORIZED"
ERROR_INVALID_REQUEST = "INVALID_REQUEST"
ERROR_SERVER_SHUTTING_DOWN = "SERVER_SHUTTING_DOWN"
ERROR_ROOM_NOT_FOUND = "ROOM_NOT_FOUND"
ERROR_ROOM_EXISTS = "ROOM_EXISTS"
ERROR_USER_NOT_FOUND = "USER_NOT_FOUND"

DEFAULT_ENCODING = "utf-8"
FRAME_HEADER_SIZE = 4
MAX_PAYLOAD_BYTES = 10 * 1024 * 1024

__all__ = [
    "ACTION_CREATE_ROOM",
    "ACTION_DISCONNECT",
    "ACTION_GET_HISTORY",
    "ACTION_GET_ROOMS",
    "ACTION_GET_ROOM_MEMBERS",
    "ACTION_JOIN_ROOM",
    "ACTION_LEAVE_ROOM",
    "ACTION_LOGIN",
    "ACTION_MESSAGE_DELIVERED",
    "ACTION_PING",
    "ACTION_REGISTER",
    "ACTION_SEND_MESSAGE",
    "ACTION_TYPING",
    "DEFAULT_ENCODING",
    "ERROR_INVALID_CREDENTIALS",
    "ERROR_INVALID_REQUEST",
    "ERROR_RATE_LIMIT_EXCEEDED",
    "ERROR_ROOM_EXISTS",
    "ERROR_ROOM_NOT_FOUND",
    "ERROR_SERVER_SHUTTING_DOWN",
    "ERROR_UNAUTHORIZED",
    "ERROR_USER_EXISTS",
    "ERROR_USER_NOT_FOUND",
    "EVENT_ERROR",
    "EVENT_NEW_MESSAGE",
    "EVENT_PRESENCE_UPDATE",
    "EVENT_RESPONSE",
    "EVENT_ROOM_UPDATE",
    "EVENT_TYPING_UPDATE",
    "FRAME_HEADER_SIZE",
    "MAX_PAYLOAD_BYTES",
    "STATUS_ERROR",
    "STATUS_SUCCESS",
]
